<a href="https://colab.research.google.com/github/shaileshmeivel/Machine-Learning/blob/main/Lab2_Exercises(ML).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **19CSE305: MACHINE LEARNING LAB 2**





ROLL NUMBER: 

## Python Basic Exercises

1. Get the values P,t,R from user and calculate compound interest. Formula to calculate compound interest annually is given by: 
        A = P(1+R/100)*t
        CI = A – P
        Input : Principle, Time, Rate
        Output : Compound Interest
2. Given a list of strings (Entered by the user), write program to get a percentage share of each word in the strings list.
        percentage = (Occurrence of a word / Total words) * 100
3. Check if  the binary representation of a number is Palindrome or not. Given an integer ‘n’ (entered by the user), write a Python function that returns true if binary representation of 'x' is palindrome and false if not.
4. Write a program to check if all digits of a number divide it. Given a number n (entered by the user), find whether all digits of n divide it or not.
5. Given a list of numbers (entered by the user), write a program to find the second largest number in that list.
        Input: [1, 2, 3, 4 ,5]
        Output: 4

In [ ]:
#Question 1 : Compound Interest
principle= float(input("Enter the principle \n"))
time = float(input("Enter the time period \n"))
rate = float(input("Enter the rate \n"))
x=1+(rate/100)
A = principle*(x**time)
CompoundInterest = A - principle
print("The compound interest is ", CompoundInterest)

Enter the principle 
10000
Enter the time period 
5
Enter the rate 
10.25
The compound interest is  6288.946267774416


In [ ]:
#Question 2: Getting percentage share of each word
string = input()
stringList = string.split(" ")
stringCheck = input()

count = 0
percentage = 0
 
for i in stringList:
  if (i==stringCheck):
    count +=1
  
percentage = (count/len(stringList))*100
print(percentage)

the car wash is the
the
40.0


In [ ]:
#Question 3: Check if a binary 
number = int(input())
binary = (bin(number)[2:])
if(binary == binary[ :: -1]):
  print("True")
else:
  print("False")

9
True


In [ ]:
#Question 5: Find 2nd largest number
size=int(input('Enter number of elements: '))
lis = []
for i in range(0,size):
  element = int(input())
  lis.append(element)

lis.sort()
print(lis[-2])


Enter number of elements: 5
4
2
1
-8
6
4


In [ ]:
#Question 5: Find 2nd largest number
lis = []
# number of elements
n = int(input("Enter number of elements : "))
  
# Below line read inputs from user using map() function 
lis = list(map(int,input("\nEnter the numbers : ").strip().split()))[:n]
 
print("\nList is - ", lis)

lis.sort()
print(lis[-2])

## Numpy Basic Exercises

1. Create a 3D array of shape 4*5*2 that contains random decimal numbers between 1 and 10.
2. Create a randomly created 1D array and Convert it to a 2D array with 2 rows.
3. Given a NumPy array of temperature values, convert the values of Centigrade degrees into Fahrenheit degrees. 
4. Write a NumPy program to count the number of dimensions, number of elements and number of bytes for each element in a given array.
5. Write a NumPy program to extract third and second elements of the first and second rows from a given (3x4) array

In [20]:
#Question 1
import numpy as np
a = np.array([[[1,2], [3,4]],
             [[0,4], [3,4]], 
             [[7,8], [5,6]],
             [[1,2], [2,3]],
             [[3,4], [5,4]]])
print(a.shape)
b = np.array([[[1,2],[3,4], [4,5], [6,7], [8,9]],
             [[1,2],[3,4], [4,5], [6,7], [8,9]],
              [[1,2],[3,4], [4,5], [6,7], [8,9]],
              [[1,2],[3,4], [4,5], [6,7], [8,9]]])
print(b.shape)
print(b.ndim)

(5, 2, 2)
(4, 5, 2)
3


In [9]:
#Question 2
import numpy as np
arrays = np.array([1,2,3,4,5,6])
newArray = arrays.reshape(2,3)
newArray

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
#Question 5
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newArray = array.reshape(3,4)
print(newArray)
print(newArray[0, 1:3])
print(newArray[1, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[2 3]
[6 7]


In [23]:
#Question 4
print(newArray.ndim)
print(newArray.size)
print(newArray.itemsize)

2
12
8
